--
-- PostgreSQL database dump
--

\restrict mge3UoVMA9ldmv4rmKDtZcbHD6P7HbKAqlMEFJnWBevNPAj5ybiVr19iJFZNWdI

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-05-25 18:32:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16512)
-- Name: classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classes (
    class_id integer NOT NULL,
    class_name character varying(100),
    schedule character varying(100),
    trainer_id integer
);


ALTER TABLE public.classes OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16511)
-- Name: classes_class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.classes_class_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.classes_class_id_seq OWNER TO postgres;

--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 225
-- Name: classes_class_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.classes_class_id_seq OWNED BY public.classes.class_id;


--
-- TOC entry 232 (class 1259 OID 16554)
-- Name: fitness_classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fitness_classes (
    id bigint NOT NULL,
    class_name character varying(255),
    schedule character varying(255),
    trainer_id bigint
);


ALTER TABLE public.fitness_classes OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16553)
-- Name: fitness_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fitness_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fitness_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16483)
-- Name: members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.members (
    member_id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    phone character varying(255),
    email character varying(255),
    membership_type character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.members OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16537)
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16482)
-- Name: members_member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.members_member_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.members_member_id_seq OWNER TO postgres;

--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 219
-- Name: members_member_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.members_member_id_seq OWNED BY public.members.member_id;


--
-- TOC entry 224 (class 1259 OID 16499)
-- Name: memberships; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.memberships (
    membership_id integer NOT NULL,
    member_id bigint,
    start_date date,
    end_date date,
    price double precision,
    id bigint NOT NULL
);


ALTER TABLE public.memberships OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16567)
-- Name: memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16498)
-- Name: memberships_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.memberships_membership_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.memberships_membership_id_seq OWNER TO postgres;

--
-- TOC entry 4975 (class 0 OID 0)
-- Dependencies: 223
-- Name: memberships_membership_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.memberships_membership_id_seq OWNED BY public.memberships.membership_id;


--
-- TOC entry 228 (class 1259 OID 16525)
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    payment_id integer NOT NULL,
    member_id bigint,
    amount double precision,
    payment_date date,
    id bigint NOT NULL
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16586)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16524)
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.payments_payment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payments_payment_id_seq OWNER TO postgres;

--
-- TOC entry 4976 (class 0 OID 0)
-- Dependencies: 227
-- Name: payments_payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.payments_payment_id_seq OWNED BY public.payments.payment_id;


--
-- TOC entry 222 (class 1259 OID 16491)
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    trainer_id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    specialization character varying(255),
    phone character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16545)
-- Name: trainers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trainers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trainers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16490)
-- Name: trainers_trainer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.trainers_trainer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.trainers_trainer_id_seq OWNER TO postgres;

--
-- TOC entry 4977 (class 0 OID 0)
-- Dependencies: 221
-- Name: trainers_trainer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.trainers_trainer_id_seq OWNED BY public.trainers.trainer_id;


--
-- TOC entry 4787 (class 2604 OID 16515)
-- Name: classes class_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes ALTER COLUMN class_id SET DEFAULT nextval('public.classes_class_id_seq'::regclass);


--
-- TOC entry 4784 (class 2604 OID 16486)
-- Name: members member_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members ALTER COLUMN member_id SET DEFAULT nextval('public.members_member_id_seq'::regclass);


--
-- TOC entry 4786 (class 2604 OID 16502)
-- Name: memberships membership_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.memberships ALTER COLUMN membership_id SET DEFAULT nextval('public.memberships_membership_id_seq'::regclass);


--
-- TOC entry 4788 (class 2604 OID 16528)
-- Name: payments payment_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments ALTER COLUMN payment_id SET DEFAULT nextval('public.payments_payment_id_seq'::regclass);


--
-- TOC entry 4785 (class 2604 OID 16494)
-- Name: trainers trainer_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers ALTER COLUMN trainer_id SET DEFAULT nextval('public.trainers_trainer_id_seq'::regclass);


--
-- TOC entry 4959 (class 0 OID 16512)
-- Dependencies: 226
-- Data for Name: classes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.classes (class_id, class_name, schedule, trainer_id) FROM stdin;
1	Yoga pentru incepatori	Luni 18:00	1
2	Fitness cardio	Miercuri 19:00	2
3	Yoga pentru incepatori	Luni 18:00	1
4	Fitness cardio	Miercuri 19:00	2
5	Yoga pentru incepatori	Luni 18:00	1
6	Fitness cardio	Miercuri 19:00	2
\.


--
-- TOC entry 4965 (class 0 OID 16554)
-- Dependencies: 232
-- Data for Name: fitness_classes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fitness_classes (id, class_name, schedule, trainer_id) FROM stdin;
1	Yoga pentru incepatori	Luni 18:00	1
\.


--
-- TOC entry 4953 (class 0 OID 16483)
-- Dependencies: 220
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.members (member_id, first_name, last_name, phone, email, membership_type, id) FROM stdin;
1	Ana	Dumitrescu	0734567890	ana@email.com	Premium	1
2	Mihai	Stan	0745678901	mihai@email.com	Basic	2
3	Ana	Dumitrescu	0734567890	ana@email.com	Premium	3
4	Mihai	Stan	0745678901	mihai@email.com	Basic	4
5	Ana	Dumitrescu	0734567890	ana@email.com	Premium	5
\.


--
-- TOC entry 4957 (class 0 OID 16499)
-- Dependencies: 224
-- Data for Name: memberships; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.memberships (membership_id, member_id, start_date, end_date, price, id) FROM stdin;
1	1	2026-04-01	2026-05-01	150	1
2	2	2026-04-10	2026-05-10	100	2
3	1	2026-04-01	2026-05-01	150	3
4	2	2026-04-10	2026-05-10	100	4
5	1	2026-04-01	2026-05-01	150	5
6	2	2026-04-10	2026-05-10	100	6
\.


--
-- TOC entry 4961 (class 0 OID 16525)
-- Dependencies: 228
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (payment_id, member_id, amount, payment_date, id) FROM stdin;
1	1	150	2026-04-01	1
2	2	100	2026-04-10	2
3	1	150	2026-04-01	3
4	2	100	2026-04-10	4
5	1	150	2026-04-01	5
6	2	100	2026-04-10	6
\.


--
-- TOC entry 4955 (class 0 OID 16491)
-- Dependencies: 222
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (trainer_id, first_name, last_name, specialization, phone, id) FROM stdin;
1	Maria	Popescu	Yoga	0712345678	1
2	Andrei	Ionescu	Fitness	0723456789	2
3	Maria	Popescu	Yoga	0712345678	3
4	Andrei	Ionescu	Fitness	0723456789	4
5	Maria	Popescu	Yoga	0712345678	5
6	Andrei	Ionescu	Fitness	0723456789	6
\.


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 225
-- Name: classes_class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.classes_class_id_seq', 6, true);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 231
-- Name: fitness_classes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fitness_classes_id_seq', 1, true);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 229
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_id_seq', 6, true);


--
-- TOC entry 4981 (class 0 OID 0)
-- Dependencies: 219
-- Name: members_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_member_id_seq', 6, true);


--
-- TOC entry 4982 (class 0 OID 0)
-- Dependencies: 233
-- Name: memberships_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.memberships_id_seq', 6, true);


--
-- TOC entry 4983 (class 0 OID 0)
-- Dependencies: 223
-- Name: memberships_membership_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.memberships_membership_id_seq', 6, true);


--
-- TOC entry 4984 (class 0 OID 0)
-- Dependencies: 234
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 6, true);


--
-- TOC entry 4985 (class 0 OID 0)
-- Dependencies: 227
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 6, true);


--
-- TOC entry 4986 (class 0 OID 0)
-- Dependencies: 230
-- Name: trainers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_id_seq', 6, true);


--
-- TOC entry 4987 (class 0 OID 0)
-- Dependencies: 221
-- Name: trainers_trainer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_trainer_id_seq', 6, true);


--
-- TOC entry 4796 (class 2606 OID 16518)
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (class_id);


--
-- TOC entry 4800 (class 2606 OID 16561)
-- Name: fitness_classes fitness_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fitness_classes
    ADD CONSTRAINT fitness_classes_pkey PRIMARY KEY (id);


--
-- TOC entry 4790 (class 2606 OID 16489)
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (member_id);


--
-- TOC entry 4794 (class 2606 OID 16505)
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (membership_id);


--
-- TOC entry 4798 (class 2606 OID 16531)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- TOC entry 4792 (class 2606 OID 16497)
-- Name: trainers trainers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainers_pkey PRIMARY KEY (trainer_id);


--
-- TOC entry 4802 (class 2606 OID 16519)
-- Name: classes classes_trainer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.trainers(trainer_id);


--
-- TOC entry 4804 (class 2606 OID 16562)
-- Name: fitness_classes fkm9pig3mnfea65ywbh8q0uvym8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fitness_classes
    ADD CONSTRAINT fkm9pig3mnfea65ywbh8q0uvym8 FOREIGN KEY (trainer_id) REFERENCES public.trainers(trainer_id);


--
-- TOC entry 4801 (class 2606 OID 16577)
-- Name: memberships memberships_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id);


--
-- TOC entry 4803 (class 2606 OID 16596)
-- Name: payments payments_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id);


-- Completed on 2026-05-25 18:32:37

--
-- PostgreSQL database dump complete
--

\unrestrict mge3UoVMA9ldmv4rmKDtZcbHD6P7HbKAqlMEFJnWBevNPAj5ybiVr19iJFZNWdI

